# Generated by Django 4.2.20 on 2025-10-07 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Настройки сайта', max_length=100, verbose_name='Название')),
                ('working_hours_per_month', models.PositiveIntegerField(default=168, verbose_name='Количество рабочих часов в месяц')),
                ('average_salary_per_month', models.PositiveIntegerField(default=3600, verbose_name='Средняя заработная плата в месяц, рублей')),
                ('professional_income_tax', models.DecimalField(decimal_places=2, default=10.0, max_digits=5, verbose_name='Налог на профессиональный доход, %')),
                ('rent_per_month', models.DecimalField(decimal_places=2, default=330.0, max_digits=10, verbose_name='Арендная плата в месяц, рублей')),
                ('utilities_per_month', models.DecimalField(decimal_places=2, default=90.0, max_digits=10, verbose_name='Коммунальные платежи в месяц, рублей')),
                ('equipment_cost', models.PositiveIntegerField(default=2000, verbose_name='Стоимость оборудования, рублей')),
                ('equipment_lifespan_months', models.PositiveIntegerField(default=96, verbose_name='Срок службы оборудования, мес.')),
                ('materials_per_month', models.DecimalField(decimal_places=2, default=20.0, max_digits=10, verbose_name='Материалы в месяц, рублей')),
                ('advertising_per_month', models.DecimalField(decimal_places=2, default=20.0, max_digits=10, verbose_name='Реклама в месяц, рублей')),
            ],
            options={
                'verbose_name': 'настройки сайта',
                'verbose_name_plural': 'настройки сайта',
            },
        ),
    ]
